spring:
  batch:
    job:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: snnLab
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

singleF2FJob:
  name: singleF2FJob
  resourcePath: /home/sinanhotamis/snn_lab/projects/spring-cloud-data-flow/spring-cloud-data-flow-batch/  #Change your application local path
  chunkSize: 10