spring:
  batch:
    job:
      enabled: true
  profiles:
    active: ${ENV}
  datasource:
    url: jdbc:postgresql://postgres:5432/dataflow
    driverClassName: org.postgresql.Driver
    username: root
    password: rootpw
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    dataflow:
      features:
        schedules-enabled: true


singlef2fjob:
  name: singleF2FJob
  #App registery mount path is identified in case of local file access Spring Cloud Data Flow(SCDF).
  #Normally SFTP, FTP, or etc.. accessing protocols should be integrated with SCDDF
  resourcePath: /root/.m2/repository/
  chunkSize: 10

